export enum ArtworkGenreEnum {
  // Classical Movements
  RENAISSANCE = 'Renaissance',
  BAROQUE = 'Baroque',
  ROMANTICISM = 'Romanticism',
  REALISM = 'Realism',
  IMPRESSIONISM = 'Impressionism',
  EXPRESSIONISM = 'Expressionism',
  CUBISM = 'Cubism',
  ART_NOUVEAU = 'Art Nouveau',
  ART_DECO = 'Art Deco',
  CONTEMPORARY = 'Contemporary',
  CONCEPTUAL_ART = 'Conceptual Art',
  HYPERREALISM = 'Hyperrealism',
  NEO_EXPRESSIONISM = 'Neo-Expressionism',
  LOWBROW = 'Lowbrow',

  // Thematic
  ABSTRACT = 'Abstract',
  FIGURATIVE = 'Figurative',
  PORTRAIT = 'Portrait',
  LANDSCAPE = 'Landscape',
  SEASCAPE = 'Seascape',
  CITYSCAPE = 'Cityscape',
  STILL_LIFE = 'Still Life',
  GENRE_SCENE = 'Genre Scene',
  NARRATIVE = 'Narrative',
  HISTORICAL = 'Historical',
  MYTHOLOGICAL = 'Mythological',
  RELIGIOUS = 'Religious',
  POLITICAL = 'Political',
  SOCIAL_COMMENTARY = 'Social Commentary',
  DARK_ART = 'Dark Art',
  GOTHIC = 'Gothic',
  MINIMALIST = 'Minimalist',
  SURREAL = 'Surreal',

  // Nature & Subjects
  NATURE = 'Nature',
  BOTANICAL = 'Botanical',
  FLORAL = 'Floral',
  ANIMAL = 'Animal',
  WILDLIFE = 'Wildlife',
  MARITIME = 'Maritime',
  SPACE = 'Space',
  VEHICLE = 'Vehicle',
  AUTOMOTIVE = 'Automotive',
  MILITARY = 'Military',
  SPORTS = 'Sports',
  FOOD_ART = 'Food Art',

  // Illustration / Industry
  ILLUSTRATION = 'Illustration',
  EDITORIAL = 'Editorial',
  CHILDRENS_ILLUSTRATION = "Children's Illustration",
  BOOK_COVER = 'Book Cover',
  GAME_ART = 'Game Art',
  MATTE_PAINTING = 'Matte Painting',
  CHARACTER_DESIGN = 'Character Design',
  CONCEPT_ART = 'Concept Art',
  FAN_ART = 'Fan Art',
  POP_CULTURE = 'Pop Culture',

  // Photography
  STREET_PHOTOGRAPHY = 'Street Photography',
  FINE_ART_PHOTOGRAPHY = 'Fine Art Photography',
  FASHION = 'Fashion',
  DOCUMENTARY = 'Documentary',

  // Environment / Context
  ENVIRONMENTAL = 'Environmental',
  INDUSTRIAL = 'Industrial',
  STREET = 'Street',
  URBAN = 'Urban',
}
