export const COOKIE_ACCESS_TOKEN: string = 'accessToken';
export const COOKIE_REFRESH_TOKEN: string = 'refreshToken';
export const COOKIE_PENDING_GOOGLE_SIGNUP: string = 'pendingGoogleSignup';
export const COOKIE_PENDING_GOOGLE_LINK: string = 'pendingGoogleLink';

export const ACCESS_TOKEN_EXPIRY_MINUTES = 15;
export const REFRESH_TOKEN_EXPIRY_DAYS = 30;
export const PENDING_GOOGLE_TOKEN_EXPIRY_MINUTES = 10;

export const ACCESS_TOKEN_EXPIRY = `${ACCESS_TOKEN_EXPIRY_MINUTES}m` as const;
export const PENDING_GOOGLE_TOKEN_EXPIRY = `${PENDING_GOOGLE_TOKEN_EXPIRY_MINUTES}m` as const;

export const ACCESS_TOKEN_MAX_AGE_MS = ACCESS_TOKEN_EXPIRY_MINUTES * 60 * 1000;
export const REFRESH_TOKEN_MAX_AGE_MS = REFRESH_TOKEN_EXPIRY_DAYS * 24 * 60 * 60 * 1000;
export const PENDING_GOOGLE_TOKEN_MAX_AGE_MS = PENDING_GOOGLE_TOKEN_EXPIRY_MINUTES * 60 * 1000;
